### ISSUE TITLE
Mirroring

### ISSUE THREAD

**Issue by larsxschneider** [RLovelett/eigen#12]
Your mirror is great! I would like to setup something similar for myself, too. Can you share the script/tool that you use for the mirroring? Thank you! 😄

**Comment by RLovelett** [comment]
Thanks! Sorry for the delay.

This is the code that runs on my Jenkins server every day.

```
git rev-parse --is-inside-git-dir || git clone --mirror hg::https://bitbucket.org/eigen/eigen .
git remote update
git gc --aggressive
git push --mirror git@github.com:RLovelett/eigen.git
```
