### ISSUE TITLE
License tag

### ISSUE THREAD

**Issue by patrikhuber** [RLovelett/eigen#13]
Hi,

GitHub shows the license of this repo as "BSD-3-Clause". Eigen is [licensed under MPL2](http://eigen.tuxfamily.org/index.php?title=Main_Page#License) though.
I think probably GitHub auto-detects this? I'm not sure how though as the repo doesn't contain a `LICENSE` file. But I think this better be corrected! :-)

**Comment by RLovelett** [comment]
GitHub pulls the license information from the LICENSE file found within the repository. Though as you note the repo does not have such a file. So obviously Git does not know.

This is not something I can fix as this is a mirror. Report upstream.
