### ISSUE TITLE
Tensor Documentation : Accessing Blocks

### ISSUE THREAD

**Issue by soulslicer** [RLovelett/eigen#15]
Good day,

Thank you for your detailed documentation of the tensor module. I would like to know how one might access a Matrix out of a 3D Tensor.

I have the following Eigen Tensor:

    Eigen::Tensor<float, 3> m(3,10,10);

I want to access the 1st matrix. In numpy I would do it as such

    m(0,:,:)

How would I do this in Eigen? The doc does not show how one might access a block of the data

**Comment by RLovelett** [comment]
This is just a mirror. Please ask this question upstream.

**Comment by RLovelett** [comment]
https://bitbucket.org/eigen/eigen/ this is the actual project.
