### ISSUE TITLE
Rewritten history?

### ISSUE THREAD

**Issue by pjknowles** [RLovelett/eigen#7]
Is there a chance that you have recently made what you might have thought was an innocuous change to your mirroring procedure, but the consequence is that all the SHAs have changed, and this has disastrous consequences for those of us using this repository as a submodule in another project.

**Comment by RLovelett** [comment]
Probably did (see #3 and #6). Trying to do the best I can with limited understand and resources. I am sorry for any inconvenience that caused you.
