### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by henryiii** [RLovelett/eigen#9]
This seems to be missing version 3.3.4 (has not been synced in a while), which has a few CUDA related fixes. I manage all external dependencies through git submodules, so this is a useful repo for me, thanks!

**Comment by RLovelett** [comment]
@henryiii thanks for the notice. My Jenkins server is offline and that is why it has stopped. I've got to figure out why the Jenkins server is not running and that should get this back online. My apologies.

**Comment by nschloe** [comment]
There's https://github.com/live-clones/eigen if you need a fallback.

**Comment by RLovelett** [comment]
@henryiii I've got the Jenkins server working again. The mirror should now be working. Thank you for the report.

**Comment by henryiii** [comment]
Thanks!
